Repository Dev-FE-1/Toy_Project_3_team4, pull requests merged in 2024-09, with the labels that each got.

#62 [Enhancement] 포스트 추가 관련 퍼블리싱 및 기능 구현
  src/App.tsx
  src/api/firebaseAuth.ts
  src/components/common/Modal.tsx
  src/components/common/buttons/ToggleButton.tsx
  src/components/layout/header/BackHeader.tsx
  src/components/layout/header/CloseHeader.tsx
  src/components/layout/navbar/NavButtonItem.tsx
  src/components/layout/navbar/Navbar.tsx
  src/components/playlist/AddPlaylistButton.tsx
  src/components/playlist/AddPlaylistModal.tsx
  src/components/playlist/Playlists.tsx
  src/components/playlistDetail/PlaylistContents.tsx
  src/components/playlistDetail/PlaylistContentsItem.tsx
  src/components/playlistDetail/PlaylistInfo.tsx
  src/constants/path.ts
  src/hooks/useAddPlaylist.ts
  src/hooks/useAddVideoToPlaylist.ts
  src/hooks/useCreatePost.ts
  src/hooks/usePlaylists.ts
  src/main.tsx
  src/pages/AddPost.tsx
  src/pages/NewPost.tsx
  src/pages/Playlist.tsx
  src/pages/PlaylistDetail.tsx
  src/pages/Profile.tsx
  src/pages/SelectPli.tsx
  src/types/playlist.ts
  src/utils/youtubeUtils.ts
Labels: enhancement

#61 [Enhancement] 드래그 앤 드롭으로 플레이리스트 순서 변경
  package-lock.json
  package.json
  src/App.tsx
  src/components/dragAndDrop/DragAndDropItem.tsx
  src/components/dragAndDrop/DragAndDropWrapper.tsx
  src/components/layout/header/BackHeader.tsx
  src/components/layout/navbar/Navbar.tsx
  src/components/playlist/VideoThumbnail.tsx
  src/components/playlistDetail/DraggablePlaylistItem.tsx
  src/components/playlistDetail/PlaylistContents.tsx
  src/components/playlistDetail/PlaylistContentsItem.tsx
  src/constants/path.ts
  src/hooks/useDragAndDrop.ts
  src/pages/AddPost.tsx
  src/pages/Playlist.tsx
  src/pages/PlaylistDetail.tsx
  src/pages/Profile.tsx
  src/types/playlist.ts
Labels: enhancement

#72 [Enhancement] 플레이리스트 관련 기타 작업들 및 타입 변경에 따른 코드 수정
  package.json
  src/api/fetchYouTubeVideoData.ts
  src/api/firebaseAuth.ts
  src/components/layout/navbar/Navbar.tsx
  src/components/playlistDetail/DraggablePlaylistItem.tsx
  src/components/playlistDetail/PlaylistContentsItem.tsx
  src/hooks/useAddPlaylist.ts
  src/hooks/useCreatePost.ts
  src/hooks/usePlaylists.ts
  src/hooks/useYouTubeVideoData.ts
  src/pages/Profile.tsx
  src/utils/date.ts
Labels: enhancement

#75 프로필 페이지 수정 페이지, 팔로우/팔로잉 페이지 추가
  package-lock.json
  src/App.tsx
  src/components/common/tabs/TabItem.tsx
  src/components/common/tabs/TabList.tsx
  src/components/post/VideoPlayButton.tsx
  src/components/post/VideoPlayer.tsx
  src/components/post/VideoPlayerButton.tsx
  src/components/profile/ProfileInfo.tsx
  src/components/user/UserInfo.tsx
  src/constants/path.ts
  src/hooks/useUserData.ts
  src/layouts/Container.tsx
  src/pages/Follow.tsx
  src/pages/Settings.tsx
  src/types/profile.ts
Labels: enhancement

#76 [Enhancement] 검색 기능 구현
  package-lock.json
  package.json
  src/api/algoliaSearch.ts
  src/api/fetchPosts.ts
  src/api/fetchUsers.ts
  src/components/user/UserInfo.tsx
  src/hooks/useSearch.ts
  src/pages/Follow.tsx
  src/pages/Search.tsx
  src/types/profile.ts
  src/types/user.ts
  src/vite-env.d.ts
Labels: enhancement

#79 [Enhancement] 포스트 컴포넌트 출력값 수정, 탭 컨텐츠 데이터 연결
  package-lock.json
  src/components/post/Post.tsx
  src/components/user/UserInfo.tsx
  src/pages/Profile.tsx
  src/pages/ProfileEdit.tsx
  src/utils/date.ts
Labels: enhancement

#80 [Enhancement] 개인정보처리방침 및 서비스 이용약관 페이지 추가 및 연결
  package-lock.json
  src/App.tsx
  src/components/layout/header/BackHeader.tsx
  src/constants/path.ts
  src/pages/PrivacyPolicyPage.tsx
  src/pages/Settings.tsx
  src/pages/SignIn.tsx
  src/pages/TermsOfServicePage.tsx
  src/styles/legal.ts
Labels: enhancement

#86 [Enhancement] Spinner 및 Loading 컴포넌트 추가
  package-lock.json
  src/components/common/Spinner.tsx
  src/components/common/loading/Loading.tsx
  src/components/common/loading/Spinner.tsx
  src/layouts/Container.tsx
  src/pages/Home.tsx
  src/pages/Profile.tsx
  src/routes/ProtectedRoute.tsx
  src/routes/PublicRoute.tsx
Labels: enhancement

#88 [Bug] 포스트 작성일 오류 수정
  src/utils/date.ts
Labels: bug

#90 [Enhancement] 팔로우 페이지 기능 및 스타일 수정
  src/api/fetchPosts.ts
  src/components/common/loading/Loading.tsx
  src/components/profile/ProfileInfo.tsx
  src/components/user/UserInfo.tsx
  src/hooks/useUserData.ts
  src/pages/Follow.tsx
  src/pages/Profile.tsx
Labels: bug, enhancement

#91 [Enhancement] 플레이리스트 관련 기능 추가
  package-lock.json
  package.json
  src/App.tsx
  src/api/fetchUsers.ts
  src/api/firebaseAuth.ts
  src/components/common/Modal.tsx
  src/components/common/buttons/FitButton.tsx
  src/components/common/buttons/IconButton.tsx
  src/components/layout/header/CloseHeader.tsx
  src/components/playlistDetail/DraggablePlaylistItem.tsx
  src/components/playlistDetail/PlaylistContents.tsx
  src/components/playlistDetail/PlaylistContentsItem.tsx
  src/components/playlistDetail/PlaylistInfo.tsx
  src/components/post/Post.tsx
  src/components/user/UserInfo.tsx
  src/constants/path.ts
  src/hooks/useAddVideoToPlaylist.ts
  src/hooks/useFetchVideoTitle.ts
  src/hooks/usePlaylists.ts
  src/hooks/usePostPlaylist.ts
  src/hooks/useRemoveVideoFromPlaylist.ts
  src/hooks/useSubscribePlaylist.ts
  src/hooks/useSubscribedPlaylists.ts
  src/hooks/useUserById.ts
  src/hooks/useUserData.ts
  src/hooks/useVideoToPlaylist.ts
  src/pages/AddPost.tsx
  src/pages/AddVideos.tsx
  src/pages/NewPost.tsx
  src/pages/Playlist.tsx
  src/pages/PlaylistDetail.tsx
  src/pages/Profile.tsx
  src/pages/SelectPli.tsx
  src/types/playlist.ts
  src/types/user.ts
  src/utils/dummy.ts
Labels: enhancement

#94 [Bug] drag and drop 오류 수정
  package-lock.json
  package.json
  src/api/fetchPlaylist.ts
  src/components/dragAndDrop/DragAndDropItem.tsx
  src/components/dragAndDrop/DragAndDropWrapper.tsx
  src/components/playlist/AddPlaylistButton.tsx
  src/components/playlist/Playlists.tsx
  src/components/playlistDetail/DraggablePlaylistItem.tsx
  src/components/playlistDetail/PlaylistContents.tsx
  src/components/playlistDetail/PlaylistContentsItem.tsx
  src/components/playlistDetail/PlaylistInfo.tsx
  src/components/post/VideoPlayer.tsx
  src/hooks/useDragAndDrop.ts
  src/main.tsx
  src/pages/AddVideos.tsx
  src/pages/PlaylistDetail.tsx
  src/types/playlist.ts
Labels: bug, enhancement

#99 [Enhancement/Design] 포스트 상세 페이지, 타임라인 스타일 수정 및 약간의 기능 추가
  src/App.tsx
  src/components/comment/CommentInput.tsx
  src/components/comment/CommentItem.tsx
  src/components/comment/CommentSection.tsx
  src/components/post/Post.tsx
  src/constants/path.ts
  src/pages/Home.tsx
  src/pages/PostDetail.tsx
Labels: enhancement, design

#101 [Enhancement] 미구현된 로직 추가 및 기타 버그 수정
  src/App.tsx
  src/components/comment/CommentInput.tsx
  src/components/comment/CommentItem.tsx
  src/components/comment/CommentSection.tsx
  src/components/playlist/AddPlaylistButton.tsx
  src/components/playlist/Playlists.tsx
  src/components/playlistDetail/PlaylistContentsItem.tsx
  src/components/playlistDetail/PlaylistInfo.tsx
  src/components/post/Post.tsx
  src/constants/path.ts
  src/hooks/useComments.ts
  src/hooks/useCreatePost.ts
  src/hooks/usePlaylists.ts
  src/hooks/useSubscribePlaylist.ts
  src/hooks/useVideoToPlaylist.ts
  src/pages/Home.tsx
  src/pages/Profile.tsx
  src/pages/SelectPli.tsx
  src/utils/video.ts
Labels: bug, enhancement

#102 [Enhancement] Avatar 컴포넌트 추가
  src/assets/images/default-avatar.svg
  src/components/comment/CommentItem.tsx
  src/components/comment/CommentSection.tsx
  src/components/common/Avatar.tsx
  src/components/playlistDetail/PlaylistContents.tsx
  src/components/playlistDetail/PlaylistInfo.tsx
  src/components/profile/ProfileInfo.tsx
  src/components/user/UserInfo.tsx
  src/types/avatar.ts
Labels: enhancement

#106 [Design] 전반적인 스타일 수정
  src/components/common/buttons/FitButton.tsx
  src/components/playlist/Playlists.tsx
  src/components/playlistDetail/PlaylistInfo.tsx
  src/pages/AddPost.tsx
  src/pages/AddVideos.tsx
  src/pages/NewPost.tsx
  src/pages/SelectPli.tsx
Labels: design

#108 [Enhancement] 404 페이지 추가
  src/App.tsx
  src/pages/NotFound.tsx
Labels: enhancement

#107 [Test] e2e 테스트 코드 작성
  .gitignore
  bun.lockb
  package-lock.json
  package.json
  playwright.config.ts
  src/api/fetchPosts.ts
  src/api/fetchUsers.ts
  src/components/comment/CommentInput.tsx
  src/components/comment/CommentItem.tsx
  src/components/comment/CommentSection.tsx
  src/components/common/buttons/FullButton.tsx
  src/components/common/buttons/ToggleButton.tsx
  src/components/common/loading/Spinner.tsx
  src/components/common/tabs/TabItem.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/navbar/NavButtonItem.tsx
  src/components/playlist/AddPlaylistButton.tsx
  src/components/playlist/Playlists.tsx
  src/components/playlistDetail/PlaylistContentsItem.tsx
  src/components/post/Post.tsx
  src/components/post/PostsTimeline.tsx
  src/layouts/Root.tsx
  src/pages/AddVideos.tsx
  src/pages/NewPost.tsx
  src/utils/randomNumber.ts
  tests/AddPlaylistButton.spec.ts
  tests/AddPost.spec.ts
  tests/Home.spec.ts
  tests/PostDetail.spec.ts
  tests/SignIn.spec.ts
  tests/addPost.byPlaylists.spec.ts
  tests/auth.setup.ts
Labels: design, test

#114 [Design] 기타 스타일 수정
  src/components/comment/CommentInput.tsx
  src/components/comment/CommentSection.tsx
  src/components/playlist/Playlists.tsx
  src/components/playlistDetail/PlaylistContentsItem.tsx
  src/components/post/Post.tsx
  src/pages/ProfileEdit.tsx
  src/styles/GlobalStyles.tsx
Labels: design

#110 [Enhancement] 유튜브 조회수 포맷팅 함수 추가
  src/components/playlistDetail/PlaylistContentsItem.tsx
  src/utils/youtubeUtils.ts
Labels: enhancement

#113 [Docs] README.md 내용 추가
  README.md
  src/assets/images/PLI.png
Labels: documentation

#121 [Hotfix] 북마크 표시 여부 로직 수정 및 포스트 유투브 링크 항상 작동하도록 수정
  src/components/post/Post.tsx
Labels: bug

#122 [Enhancement] 삭제, 추가 기능에 토스트 추가
  src/components/playlistDetail/PlaylistContentsItem.tsx
  src/components/playlistDetail/PlaylistInfo.tsx
  src/pages/AddPost.tsx
  src/pages/AddVideos.tsx
  src/pages/NewPost.tsx
  src/pages/ProfileEdit.tsx
  src/pages/SelectPli.tsx
Labels: enhancement

#125 [Design] Modal, Toast, Navbar 그 외 자잘한 스타일 수정
  src/components/comment/CommentInput.tsx
  src/components/common/GradientIcon.tsx
  src/components/common/Toast.tsx
  src/components/common/modals/AddFixModal.tsx
  src/components/common/modals/Modal.tsx
  src/components/common/modals/OptionModal.tsx
  src/components/layout/navbar/NavItem.tsx
  src/components/layout/navbar/Navbar.tsx
  src/components/playlistDetail/PlaylistContentsItem.tsx
  src/components/playlistDetail/PlaylistInfo.tsx
  src/components/post/Post.tsx
  src/components/user/UserInfo.tsx
  src/pages/ProfileEdit.tsx
  src/styles/GlobalStyles.tsx
Labels: design

#127 [Enhancement] 포스트 상세 페이지 드롭다운을 모달로 변경 및 EmptyMessage 컴포넌트 추가
  src/components/EmptyMessage.tsx
  src/components/comment/CommentItem.tsx
  src/components/comment/CommentSection.tsx
  src/components/playlist/Playlists.tsx
  src/pages/Profile.tsx
  src/styles/GlobalStyles.tsx
Labels: enhancement

#129 [Enhancement] 파일 이름 수정 및 헤더 뒤로가기 버튼 클릭 시 경로 수정
  src/App.tsx
  src/api/fetchPosts.ts
  src/components/playlistDetail/PlaylistContentsItem.tsx
  src/pages/AddPost.tsx
  src/pages/PlaylistDetail.tsx
  src/pages/PrivacyPolicy.tsx
  src/pages/SelectPli.tsx
  src/pages/TermsOfService.tsx
  tests/addPlaylistButton.spec.ts
  tests/addPost.spec.ts
  tests/addPostByPlaylists.spec.ts
  tests/home.spec.ts
  tests/postDetail.spec.ts
  tests/signIn.spec.ts
Labels: enhancement

#135 [Enhancement] 로딩 스피너 추가
  src/components/playlistDetail/PlaylistContentsItem.tsx
  src/pages/Playlist.tsx
  src/pages/Profile.tsx
Labels: enhancement

#132 [Enhancement] 토스트 메세지 코드, 스타일 수정
  src/components/common/Toast.tsx
  src/components/common/modals/AddFixModal.tsx
  src/components/playlistDetail/PlaylistInfo.tsx
  src/pages/AddPost.tsx
Labels: enhancement

#139 [Bug] 프로필 수정 페이지 빈 닉네임 허용 x
  src/components/playlistDetail/PlaylistInfo.tsx
  src/pages/ProfileEdit.tsx
Labels: bug

#136 [Enhancement] 포스트 수정 및 삭제 기능 구현
  src/components/playlistDetail/PlaylistInfo.tsx
  src/components/post/Post.tsx
  src/hooks/useDeletePost.ts
  src/hooks/useLikedPosts.ts
  src/hooks/useModifyPost.ts
  src/hooks/usePostById.ts
  src/hooks/useUserPosts.ts
  src/pages/NewPost.tsx
  src/pages/Profile.tsx
  src/pages/SelectPli.tsx
Labels: enhancement

#141 [Bug] 타임라인 게시물 중복 해결, 타임라인에 본인 포스트가 올라오지 않는 오류 해결(#137)
  src/api/fetchPosts.ts
  src/hooks/useFilteredPostsTimelines.ts
Labels: bug

#140 [Bug] 플레이리스트 상세 페이지 경로 문제 해결
  src/pages/AddVideos.tsx
  src/pages/PlaylistDetail.tsx
Labels: bug

#143 [Docs] README.md 업데이트
  README.md
  src/assets/images/PAGES.png
Labels: documentation

#155 [deploy] pli-one.vercel.app으로 배포 도메인 변경, 배포 사이트 흰화면 나오는 버그 해결
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  .github/workflows/git push into another repo to deploy repo.yml
  build.sh
  functions/.eslintrc.cjs
  functions/.gitignore
  functions/.prettierrc
  functions/bun.lockb
  functions/package-lock.json
  functions/package.json
  functions/src/index.ts
  functions/tsconfig.dev.json
  functions/tsconfig.json
  package-lock.json
  package.json
  vercel.json
Labels: bug, deploy

#157 [Refactor] PlaylistDetail 페이지 분리
  src/components/playlist/VideoInfo.tsx
  src/components/playlistDetail/DraggablePlaylist.tsx
  src/components/playlistDetail/DraggablePlaylistItem.tsx
  src/components/playlistDetail/PlaylistContentsItem.tsx
  src/components/playlistDetail/PlaylistInfo.tsx
  src/components/playlistDetail/PlaylistItem.tsx
  src/components/playlistDetail/SelectablePlaylist.tsx
  src/components/playlistDetail/SelectablePlaylistItem.tsx
  src/pages/AddVideos.tsx
  src/pages/PlaylistDetail.tsx
  src/pages/SelectVideo.tsx
  src/types/playlist.ts
Labels: refactor

#156 [Refactor] 포스트 등록 후 toast 메세지 딜레이
  src/pages/Home.tsx
  src/pages/NewPost.tsx
Labels: refactor

#159 [Test] 포스트에 플레이리스트 제목이 제대로 뜨는지 테스트코드 추가
  src/components/post/Post.tsx
  tests/auth.setup.ts
  tests/playlistTitle.spec.ts
Labels: test

#164 [Enhancement] Input 값 최대 길이 설정
  src/components/comment/CommentInput.tsx
  src/components/comment/CommentItem.tsx
  src/components/comment/CommentSection.tsx
  src/components/common/inputs/BaseInput.tsx
  src/components/common/inputs/Input.tsx
  src/components/common/inputs/InputCount.tsx
  src/components/common/inputs/Textarea.tsx
  src/pages/ProfileEdit.tsx
  src/styles/input.ts
Labels: enhancement

#170 [Enhancement] 포스트 추가 페이지들을 모달로 처리 및 모달과 오버레이를 전역으로 상태 관리하도록 변경
  src/components/comment/CommentItem.tsx
  src/components/common/modals/AddFixModal.tsx
  src/components/common/modals/FullModal.tsx
  src/components/common/modals/Modal.tsx
  src/components/common/modals/OptionModal.tsx
  src/components/common/modals/Overlay.tsx
  src/components/layout/header/BackHeader.tsx
  src/components/layout/header/CloseHeader.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/navbar/NavButtonItem.tsx
  src/components/playlist/AddPlaylistButton.tsx
  src/components/playlistDetail/DraggablePlaylistItem.tsx
  src/components/playlistDetail/PlaylistInfo.tsx
  src/components/post/Post.tsx
  src/hooks/useLikedPosts.ts
  src/hooks/useModalWithOverlay.ts
  src/hooks/useModifyPost.ts
  src/hooks/usePlaylists.ts
  src/hooks/useVideoToPlaylist.ts
  src/main.tsx
  src/pages/AddPost.tsx
  src/pages/Follow.tsx
  src/pages/NewPost.tsx
  src/pages/PlaylistDetail.tsx
  src/pages/PostDetail.tsx
  src/pages/PrivacyPolicy.tsx
  src/pages/ProfileEdit.tsx
  src/pages/SelectPli.tsx
  src/pages/SelectVideo.tsx
  src/pages/Settings.tsx
  src/pages/TermsOfService.tsx
  src/stores/modalStore.ts
Labels: refactor

#172 [Refactor] 모달 관련 동작 수정 및 헤더 제목 등 수정
  src/components/layout/navbar/NavButtonItem.tsx
  src/pages/AddPost.tsx
  src/pages/SelectPli.tsx
  src/pages/SelectVideo.tsx
Labels: refactor

#178 [Enhancement] 다름 사람의 플리에서 비디오를 내 플리에 추가할때 중복된 비디오가 추가되지 않도록 수정
  src/components/playlist/Playlists.tsx
  src/pages/SelectPli.tsx
Labels: enhancement
