Repository Dev-FE-1/Toy_Project_3_team4, pull requests merged in 2024-08, with the labels that each got.

#22 [enhancement] 공통 스타일 설정
  index.html
  package-lock.json
  package.json
  src/App.css
  src/index.css
  src/main.tsx
  src/styles/GlobalStyles.ts
  src/styles/GlobalStyles.tsx
  src/styles/Theme.ts
  src/styles/reset.css
  src/types/emotion.d.ts
  tsconfig.app.json
Labels: setting, design

#25 [fix] 공통 스타일 오류 수정
  src/styles/GlobalStyles.tsx
Labels: bug

#27 HotFix/eslint-config-20 eslint 재설정
  .eslintrc.cjs
  .gitattributes
  .github/workflows/firebase-hosting-pull-request.yml
  .gitignore
  .prettierignore
  .prettierrc
  bun.lockb
  eslint.config.js
  functions/tsconfig.dev.json
  lefthook.yml
  package-lock.json
  package.json
  src/api/firebaseApp.ts
  src/api/firebaseAuth.ts
  src/main.tsx
  src/styles/GlobalStyles.tsx
  tsconfig.app.json
  tsconfig.node.json
  vite.config.ts
Labels: bug, setting

#31 [Enhancement] Navbar 컴포넌트 추가
  package-lock.json
  package.json
  src/App.tsx
  src/components/common/Navigation.tsx
  src/components/layout/Navbar/NavItem.tsx
  src/components/layout/Navbar/Navbar.tsx
  src/constants/path.ts
  src/layouts/Root.tsx
  src/pages/AddPost.tsx
  src/pages/Home.tsx
  src/pages/Playlist.tsx
  src/pages/Profile.tsx
  src/pages/Search.tsx
  src/styles/GlobalStyles.tsx
  src/styles/theme.ts
  src/types/emotion.d.ts
Labels: enhancement

#35 [settings] eslint lefthook 재설정, 백엔드 서버 설정
  .gitignore
  functions/.eslintrc.cjs
  functions/.eslintrc.js
  functions/.prettierrc
  functions/bun.lockb
  functions/package-lock.json
  functions/package.json
  functions/src/index.ts
  functions/tsconfig.dev.json
  functions/tsconfig.json
  lefthook.yml
  package-lock.json
  package.json
  src/components/common/buttons/FitButton.tsx
  src/components/common/buttons/FullButton.tsx
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
Labels: setting, backend

#38 [Feat] Favicon 추가
  index.html
  src/assets/images/favicon.ico
  src/assets/images/favicon/favicon.ico
  src/assets/images/favicon/favicon.svg
  src/assets/react.svg
Labels: enhancement

#37 [Enhancement] NavButtonItem 컴포넌트 추가
  src/components/layout/Navbar/NavButtonItem.tsx
  src/components/layout/Navbar/NavItem.tsx
  src/components/layout/Navbar/Navbar.tsx
Labels: enhancement

#39 [Enhancement] input, textarea 컴포넌트 추가
  src/components/common/Input.tsx
  src/components/common/inputs/BaseInput.tsx
  src/components/common/inputs/Input.tsx
  src/components/common/inputs/Textarea.tsx
  src/styles/GlobalStyles.tsx
  src/styles/input.ts
  src/styles/theme.ts
  src/utils/randomId.ts
Labels: enhancement

#32 [Enhancement] 토스트 컴포넌트 추가
  src/components/common/Toast.tsx
  src/components/common/buttons/FitButton.tsx
  src/components/common/buttons/FullButton.tsx
  src/main.tsx
  src/store/store.ts
  src/store/toastStore.ts
Labels: enhancement

#41 [Enhancement] Tab 메뉴 컴포넌트
  src/components/common/tabs/TabContent.tsx
  src/components/common/tabs/TabItem.tsx
  src/components/common/tabs/TabList.tsx
  src/components/common/tabs/TabMenu.tsx
  src/pages/Profile.tsx
Labels: enhancement

#42 [Enhancement] 모달 컴포넌트 생성
  .github/workflows/firebase-hosting-pull-request.yml
  package-lock.json
  package.json
  src/components/common/Modal.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/Modal/SampleModal.tsx
Labels: enhancement

#45 [Enhancement] 구글 로그인 및 로그아웃 기능 구현
  package-lock.json
  package.json
  src/App.tsx
  src/api/firebaseApp.ts
  src/api/firebaseAuth.ts
  src/assets/images/onboarding1.png
  src/assets/images/onboarding2.png
  src/components/common/GradientIcon.tsx
  src/components/onboarding/ChatBubble.tsx
  src/components/onboarding/OnboardingSwiper.tsx
  src/constants/path.ts
  src/layouts/Container.tsx
  src/layouts/Root.tsx
  src/pages/Settings.tsx
  src/pages/SignIn.tsx
  src/routes/ProtectedRoute.tsx
  src/routes/PublicRoute.tsx
  src/utils/gradient.ts
Labels: enhancement

#50 [Enhancement] playlist 페이지 퍼블리싱 및 스타일 오류 수정
  src/components/common/tabs/TabItem.tsx
  src/components/common/tabs/TabList.tsx
  src/components/layout/Navbar/Navbar.tsx
  src/components/layout/header/Header.tsx
  src/components/onboarding/OnboardingSwiper.tsx
  src/components/playlist/AddPlaylistButton.tsx
  src/components/playlist/PlaylistThumbnail.tsx
  src/components/playlist/Playlists.tsx
  src/layouts/Container.tsx
  src/layouts/Root.tsx
  src/pages/Playlist.tsx
  src/styles/GlobalStyles.tsx
  src/types/playlist.ts
Labels: enhancement, design

#52 [Enhancement] playlist 상세 페이지 퍼블리싱
  src/App.tsx
  src/components/common/buttons/FitButton.tsx
  src/components/layout/header/BackHeader.tsx
  src/components/playlist/PlaylistThumbnail.tsx
  src/components/playlist/Playlists.tsx
  src/components/playlist/PrivateLabel.tsx
  src/components/playlist/VideoThumbnail.tsx
  src/components/playlistDetail/PlaylistContents.tsx
  src/components/playlistDetail/PlaylistContentsItem.tsx
  src/components/playlistDetail/PlaylistInfo.tsx
  src/components/user/UserInfo.tsx
  src/pages/Playlist.tsx
  src/pages/PlaylistDetail.tsx
  src/styles/GlobalStyles.tsx
  src/styles/theme.ts
  src/types/playlist.ts
  src/types/user.ts
  src/utils/date.ts
  src/utils/dummy.ts
Labels: enhancement, design

#55 [Enhancement] 검색 페이지 Header 수정 및 debounce 적용
  package-lock.json
  package.json
  src/components/layout/header/BackHeader.tsx
  src/components/layout/header/SearchHeader.tsx
  src/hooks/useDebounce.ts
  src/pages/Search.tsx
Labels: enhancement

#59 [Enhancement] 프로필 페이지 퍼블리싱 및 포스트 컴포넌트 추가 및 설정 페이지 연결&헤더 추가
  package-lock.json
  package.json
  src/App.tsx
  src/assets/images/default-avatar.svg
  src/components/common/tabs/TabItem.tsx
  src/components/layout/navbar/NavItem.tsx
  src/components/layout/navbar/Navbar.tsx
  src/components/post/Posts.tsx
  src/components/post/VideoPlayer.tsx
  src/components/post/VideoPlayerButton.tsx
  src/components/profile/ProfileInfo.tsx
  src/constants/path.ts
  src/hooks/useAuth.ts
  src/hooks/useUserData.ts
  src/pages/Profile.tsx
  src/pages/ProfileEdit.tsx
  src/pages/Settings.tsx
  src/types/post.ts
  src/types/profile.ts
  src/utils/dummy.ts
Labels: enhancement
